codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "vendor/**"
  - "**/zz_generated*.go"
  - "test/**"
  - "hack/**"
  - "config/**"
  - "bundle/**"
  - "docs/**"

flags:
  unit-tests:
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
