resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: operator
  newName: registry.redhat.io/openshift-builds/openshift-builds-rhel9-operator
  digest: sha256:b554eb5edc4466416b63e617c0218a568673afb47b9edffa96d8a353f1eba372
