apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app: openshift-builds-operator
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app: openshift-builds-operator
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: openshift-builds-operator
        control-plane: controller-manager
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /operator
        args:
        - --leader-elect
        image: operator:latest
        imagePullPolicy: Always
        name: operator
        env:
          # TODO: This needs code changes upstream
          # - name: USE_MANAGED_WEBHOOK_CERTS
          #   value: "false"
          - name: PLATFORM
            value: "openshift"
          - name: IMAGE_SHIPWRIGHT_SHIPWRIGHT_BUILD
            value: registry.redhat.io/openshift-builds/openshift-builds-controller-rhel9@sha256:1693bfeb4177860678417b3a1701b38e3f011575720fdd7dc16dc07fe38cf759
          - name: IMAGE_SHIPWRIGHT_GIT_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-git-cloner-rhel9@sha256:afd2e5efb4e3bf9b145b9a25f067375de928b8ef4b5148cb6d797240f237c868
          - name: IMAGE_SHIPWRIGHT_IMAGE_PROCESSING_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-image-processing-rhel9@sha256:f9e453ab16f1e4038cc296752ebd43ce4393819e35e0eb6d8c37eb6649e3b62c
          - name: IMAGE_SHIPWRIGHT_BUNDLE_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-image-bundler-rhel9@sha256:3c35a2fd40b19862694a65dfd4dd3bbde1f1b31e05d3385d5575836f83e091dc
          - name: IMAGE_SHIPWRIGHT_WAITER_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-waiters-rhel9@sha256:b6da3d83a44436c60aa1b070462e2f6483dacda492c44cb2f6e35bc11d844908
          - name: IMAGE_SHIPWRIGHT_SHIPWRIGHT_BUILD_WEBHOOK
            value: registry.redhat.io/openshift-builds/openshift-builds-webhook-rhel9@sha256:e17919662c7cee1aef4c7499bfc04e924d8b9de4b8d20e6bb9760dcb061ee05d
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
