apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app: openshift-builds-operator
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app: openshift-builds-operator
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: openshift-builds-operator
        control-plane: controller-manager
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /operator
        args:
        - --leader-elect
        image: operator:latest
        imagePullPolicy: Always
        name: operator
        env:
          # TODO: This needs code changes upstream
          # - name: USE_MANAGED_WEBHOOK_CERTS
          #   value: "false"
          - name: PLATFORM
            value: "openshift"
          - name: IMAGE_SHIPWRIGHT_SHIPWRIGHT_BUILD
            value: registry.redhat.io/openshift-builds/openshift-builds-controller-rhel9@sha256:b1334a19dafeb33c02198d9ed2f5b336f1ce5d42aa4071f57fa4d2e979617edb
          - name: IMAGE_SHIPWRIGHT_GIT_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-git-cloner-rhel9@sha256:65fa69dda5507dcb760a6fe93dfed57bf0ffea0fc20554317f0ff74114cfb25c
          - name: IMAGE_SHIPWRIGHT_IMAGE_PROCESSING_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-image-processing-rhel9@sha256:dae3bd802c62cd9ea7ad53687d7323f7515d94cb00e518ddf831d5eb16807c71
          - name: IMAGE_SHIPWRIGHT_BUNDLE_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-image-bundler-rhel9@sha256:2426a2483808ba2d64475080479251d796f1bca7a36e6d34f249e17797681479
          - name: IMAGE_SHIPWRIGHT_WAITER_CONTAINER_IMAGE
            value: registry.redhat.io/openshift-builds/openshift-builds-waiters-rhel9@sha256:8223f72857252e10862caa3c6f39b781e81ae2757f665f1c7253942b038c4783
          - name: IMAGE_SHIPWRIGHT_SHIPWRIGHT_BUILD_WEBHOOK
            value: registry.redhat.io/openshift-builds/openshift-builds-webhook-rhel9@sha256:41fff37f036a38475b984fdb7144825533237f069388c17483fc4ed3489372d8
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
