apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: openshift-builds
    app.kubernetes.io/version: v1.1.0
  name: openshift-builds-manager-role
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/status
  verbs:
  - get
  - patch
  - update
