apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: source-to-image-java-build
spec:
  description: A sample Build using source-to-image BuildStrategy with java builder image
  snippet: false
  targetResource:
    apiVersion: shipwright.io/v1beta1
    kind: Build
  title: Source-to-Image Java Build
  yaml: |
    apiVersion: shipwright.io/v1beta1
    kind: Build
    metadata:
      name: s2i-java-build
    spec:
      source: 
        type: Git
        git:
          url: https://github.com/redhat-openshift-builds/samples/
        contextDir: s2i-build/java
      strategy: 
        name: source-to-image
        kind: ClusterBuildStrategy
      paramValues: 
      - name: builder-image
        value: registry.access.redhat.com/ubi9/openjdk-11
      output:
        # The "namespace" in the image needs to be replaced with the namespace name where related build exists.
        # If the following image value is passed as is, the pod will error out while pushing the image due to authentication failures.
        image: image-registry.openshift-image-registry.svc:5000/namespace/s2i-java-example
