apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: buildah-build
spec:
  description: A sample Build using buildah BuildStrategy
  snippet: false
  targetResource:
    apiVersion: shipwright.io/v1beta1
    kind: Build
  title: Buildah Build
  yaml: |
    apiVersion: shipwright.io/v1beta1
    kind: Build
    metadata:
      name: buildah-golang-build
    spec:
      source:
        type: Git
        git:
          url: https://github.com/redhat-openshift-builds/samples/
        contextDir: buildah-build
      strategy:
        name: buildah
        kind: ClusterBuildStrategy
      paramValues:
      - name: dockerfile
        value: Dockerfile
      output:
        # The "namespace" in the image needs to be replaced with the namespace name where related build exists.
        # If the following image value is passed as is, the pod will error out while pushing the image due to authentication failures.
        image: image-registry.openshift-image-registry.svc:5000/namespace/sample-go-app
