apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: source-to-image-nodejs-build
spec:
  description: A sample Build using source-to-image BuildStrategy with nodejs builder image
  snippet: false
  targetResource:
    apiVersion: shipwright.io/v1beta1
    kind: Build
  title: Source-to-Image Nodejs Build
  yaml: |
    apiVersion: shipwright.io/v1beta1
    kind: Build
    metadata:
      name: s2i-nodejs-build
    spec:
      source:
        type: Git
        git:
          url: https://github.com/redhat-openshift-builds/samples/
        contextDir: s2i-build/nodejs
      strategy:
        name: source-to-image
        kind: ClusterBuildStrategy
      paramValues:
      - name: builder-image
        value: quay.io/centos7/nodejs-12-centos7:master
      output:
        # The "namespace" in the image needs to be replaced with the namespace name where related build exists.
        # If the following image value is passed as is, the pod will error out while pushing the image due to authentication failures.
        image: image-registry.openshift-image-registry.svc:5000/namespace/s2i-nodejs-example
