package controller

// +kubebuilder:rbac:groups=apps,resources=deployments,namespace=openshift-builds,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=apps,resources=deployments,namespace=openshift-builds,resourceNames=shipwright-build-controller,verbs=update;patch;delete
// +kubebuilder:rbac:groups=apps,resources=deployments/finalizers,namespace=openshift-builds,resourceNames=shipwright-build-controller,verbs=update
// +kubebuilder:rbac:groups=apps,resources=deployments,namespace=openshift-builds,resourceNames=shipwright-build-webhook,verbs=update;patch;delete
// +kubebuilder:rbac:groups=apps,resources=deployments/finalizers,namespace=openshift-builds,resourceNames=shipwright-build-webhook,verbs=update
// +kubebuilder:rbac:groups=core,resources=namespaces,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=core,resources=configmaps;services,namespace=openshift-builds,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,resources=secrets,namespace=openshift-builds,verbs=get;list;watch
// +kubebuilder:rbac:groups=core,resources=serviceaccounts,namespace=openshift-builds,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=core,resources=serviceaccounts,namespace=openshift-builds,resourceNames=shipwright-build-controller,verbs=update;patch;delete
// +kubebuilder:rbac:groups=core,resources=serviceaccounts,namespace=openshift-builds,resourceNames=shipwright-build-webhook,verbs=update;patch;delete
// +kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=apiextensions.k8s.io,resources=customresourcedefinitions,resourceNames=builds.shipwright.io;buildruns.shipwright.io;buildstrategies.shipwright.io;clusterbuildstrategies.shipwright.io,verbs=update;patch;delete
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=clusterroles,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=clusterroles,resourceNames=shipwright-build-aggregate-edit;shipwright-build-aggregate-view;shipwright-build-controller,verbs=update;patch;delete
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=clusterrolebindings,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=clusterrolebindings,resourceNames=shipwright-build-controller,verbs=update;patch;delete
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=roles,namespace=openshift-builds,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=roles,namespace=openshift-builds,resourceNames=shipwright-build-controller,verbs=update;patch;delete
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=rolebindings,namespace=openshift-builds,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=rbac.authorization.k8s.io,resources=rolebindings,namespace=openshift-builds,resourceNames=shipwright-build-controller,verbs=update;patch;delete
// +kubebuilder:rbac:groups=shipwright.io,resources=clusterbuildstrategies,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=operator.shipwright.io,resources=shipwrightbuilds,verbs=get;list;watch;update;patch
// +kubebuilder:rbac:groups=operator.shipwright.io,resources=shipwrightbuilds/finalizers,verbs=update
// +kubebuilder:rbac:groups=operator.shipwright.io,resources=shipwrightbuilds/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=operator.tekton.dev,resources=tektonconfigs,verbs=get;list;create
// +kubebuilder:rbac:groups=cert-manager.io,resources=issuers,namespace=openshift-builds,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=cert-manager.io,resources=issuers,namespace=openshift-builds,resourceNames=selfsigned-issuer,verbs=update;patch;delete
// +kubebuilder:rbac:groups=cert-manager.io,resources=certificates,namespace=openshift-builds,verbs=get;list;watch;create
// +kubebuilder:rbac:groups=cert-manager.io,resources=certificates,namespace=openshift-builds,resourceNames=shipwright-build-webhook-cert,verbs=update;patch;delete
