# permissions for end users to view openshiftbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftbuild-viewer
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/status
  verbs:
  - get
