# permissions for end users to edit openshiftbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftbuild-editor
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/status
  verbs:
  - get
