---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - limitranges
  - namespaces
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - shipwright-build-controller
  resources:
  - serviceaccounts
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resourceNames:
  - shipwright-build-webhook
  resources:
  - serviceaccounts
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  - admissionregistration.k8s.io/v1beta1
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - buildruns.shipwright.io
  - builds.shipwright.io
  - buildstrategies.shipwright.io
  - clusterbuildstrategies.shipwright.io
  resources:
  - customresourcedefinitions
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - sharedconfigmaps.sharedresource.openshift.io
  - sharedsecrets.sharedresource.openshift.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - shipwright-build-controller
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resourceNames:
  - shipwright-build-webhook
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resourceNames:
  - shipwright-build-controller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resourceNames:
  - shipwright-build-webhook
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - cert-manager.io
  resourceNames:
  - shipwright-build-webhook-cert
  resources:
  - certificates
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resourceNames:
  - selfsigned-issuer
  resources:
  - issuers
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.tekton.dev
  resources:
  - tektonconfigs
  verbs:
  - create
  - get
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - shipwright-build-controller
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - shipwright-build-webhook
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - shipwright-build-aggregate-edit
  resources:
  - clusterroles
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - shipwright-build-aggregate-view
  resources:
  - clusterroles
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - sharedresource.openshift.io
  resources:
  - sharedconfigmaps
  - sharedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shipwright.io
  resources:
  - clusterbuildstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
