apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-driver-shared-resource
roleRef:
  kind: ClusterRole
  name: shared-resource-subject-access-reviewer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: system
