apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-driver-shared-resource
rules:
  - apiGroups: ["sharedresource.openshift.io"]
    resources: ["sharedconfigmaps", "sharedsecrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
