kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
      - secrets
      - limitranges
      - namespaces
      - services
    verbs:
      - '*'
  - apiGroups:
      - admissionregistration.k8s.io
      - admissionregistration.k8s.io/v1beta1
    resources:
      - validatingwebhookconfigurations
    verbs:
      - '*'
