# permissions for end users to view shipwrightbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shipwrightbuild-viewer-role
rules:
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds/status
  verbs:
  - get
