kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-controller-namespace
roleRef:
  kind: ClusterRole
  name: build-controller-namespace
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: system
