---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-aggregate
roleRef:
  kind: ClusterRole
  name: build-aggregate
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: operator
  namespace: system
