apiVersion: operator.openshift.io/v1alpha1
kind: OpenShiftBuild
metadata:
  name: openshiftbuild
spec:
  sharedResource:
    state: Enabled
  shipwright:
    build:
      state: Enabled
  sharedResource:
    state: Enabled
