apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: unit-test
spec:
  description: Runs unit test for OpenShift Builds Operator.
  params:
  - default: -race -cover -v
    description: Flags to use for the test command
    name: GO_TEST_FLAGS
  - default: linux
    description: Operating system to use for testing
    name: GOOS
  - default: amd64
    description: System architecture to use for testing
    name: GOARCH
  - default: auto
    description: Go module support
    name: GO111MODULE
  - default: ""
    description: Go caching directory path
    name: GOCACHE
  - default: ""
    description: Go mod caching directory path
    name: GOMODCACHE
  - description: The Trusted Artifact URI pointing to the artifact with the application source code.
    name: SOURCE_ARTIFACT
    type: string
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
        readOnly: false
    # run as root to be able to do write operations in the run-test task
    securityContext:
      runAsUser: 0
  steps:
  # step to fetch the Trusted Artifact and make it available to the next steps.
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
    args:
      - use
      - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: run-test
    image: registry.access.redhat.com/ubi9/go-toolset:9.6-1752083840@sha256:6fd64cd7f38a9b87440f963b6c04953d04de65c35b9672dbd7f1805b0ae20d09
    env:
    - name: GOOS
      value: $(params.GOOS)
    - name: GOARCH
      value: $(params.GOARCH)
    - name: GO_TEST_FLAGS
      value: $(params.GO_TEST_FLAGS)
    - name: GO111MODULE
      value: $(params.GO111MODULE)
    - name: GOCACHE
      value: $(params.GOCACHE)
    - name: GOMODCACHE
      value: $(params.GOMODCACHE)
    script: |
      #!/usr/bin/env bash
      set -eux
      git config --global --add safe.directory "$(pwd)"
      make test
    workingDir: /var/workdir/source
  volumes:
    # volume to store a copy of the source code accessible only to this Task.
    - name: workdir
      emptyDir: {}
