apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-openshift-builds/operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "builds-1.6" &&
      (
        files.all.exists(x, x.matches('bundle/')) ||
        files.all.exists(x, x.matches('bundle.Dockerfile')) ||
        files.all.exists(x, x.matches('.tekton/openshift-builds-operator-bundle-pull-request.yaml'))
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-builds-1-6
    appstudio.openshift.io/component: openshift-builds-operator-bundle-1-6
    pipelines.appstudio.openshift.io/type: build
  name: openshift-builds-operator-bundle-1-6-on-pull-request
  namespace: rh-openshift-builds-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds-operator-bundle-1-6:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: bundle.Dockerfile
    - name: build-source-image
      value: "true"
    - name: hermetic
      value: "true"
    - name: build-platforms
      value:
        - linux/x86_64
    - name: build-image-index
      value: "false"
    - name: image-append-platform
      value: "false"
  pipelineRef:
    params:
      - name: url
        value: https://github.com/redhat-openshift-builds/release.git
      - name: revision
        value: main
      - name: pathInRepo
        value: /pipelines/konflux-build-multi-platform.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-openshift-builds-operator-bundle-1-6
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
